version: '3.7'
services: 
  php-74:
    container_name: php-74
    ports:
      - 19074:9000
    build:
      context: php-74
    networks:
      - htdf
    volumes:
      - ${BACKEND_ROOT}:${BACKEND_ROOT}
      - ./php-74/config/php.ini:/usr/local/etc/php/php.ini
      - ./php-74/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-74/entrypoint.sh:/entrypoint.sh
      - ./php-74/config/conf.d:/usr/local/etc/php/conf.d
      - ./logs:/logs
    environment:
      TZ: ${TZ}
      BACKEND_ROOT: ${BACKEND_ROOT}
    entrypoint: /entrypoint.sh

  php-81:
    container_name: php-81
    ports:
      - 19081:9000
    build:
      context: php-81
    networks:
      - htdf
    volumes:
      - ${BACKEND_ROOT}:${BACKEND_ROOT}
      - ./php-81/config/php.ini:/usr/local/etc/php/php.ini
      - ./php-81/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-81/entrypoint.sh:/entrypoint.sh
      - ./php-81/config/conf.d:/usr/local/etc/php/conf.d
      - ./logs:/logs
    environment:
      TZ: ${TZ}
      BACKEND_ROOT: ${BACKEND_ROOT}
    entrypoint: /entrypoint.sh

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 12100:80
    depends_on:
      - php-74
      - php-81
      - redis
    networks:
      - htdf
    volumes:
      - ${BACKEND_ROOT}:${BACKEND_ROOT}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./logs:/logs
    environment:
      TZ: ${TZ}
      VHOST_LISTEN_ADDRESS: localhost
      BACKEND_ROOT: ${BACKEND_ROOT}
    entrypoint: /entrypoint.sh

  redis:
    image: redis:5-alpine
    container_name: redis
    volumes:
      - redis:/data
      - ./redis/redis.conf:/redis.conf
    ports:
      - 12200:6379
    networks:
      - htdf
    command: ['redis-server', '/redis.conf']

networks:
  htdf:

volumes:
  redis:
  webser: